[[language]]
name = "bat"
scope = "source.bat"
indent = {tab-width = 1, unit = " "}
file-types = ["bat", "cmd"]
comment-token = "::"
language-servers = ["scls"]

[[language]]
name = "rust"
auto-format = true
indent = {tab-width = 4, unit = "    "}
language-servers = ["scls", "rust-analyzer"]


[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py", "pyi", "py3", "pyw", "pt1", ".pythonstartup", ".pythonrc", "SConstruct"]
shebangs = ["python"]
roots = [".","steup.py", "setup.cfg", "pyproject.toml"]
comment-token = "#"
language-servers = ["ruff", "pyright", "scls"]
indent = {tab-width = 4, unit = "    "}
formatter = {command = "ruff", args=["format", "--quiet", "-"]}
auto-format = true

[[language]]
name = "json"
auto-format = true
formatter = {command = "npx", args = ["prettier", "--parser", "json"]}
indent = { tab-width = 2, unit = "  "}

[[language]]
name = "powershell"
scope = "source.ps1"
roots = [".git", "."]
file-types = ["ps1", "psm"]
comment-token = "#"
indent = {tab-width = 2, unit = "  "}
language-servers = ["scls"]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]


[language-server.pyright.config.diagnosticSeverityOverrides]
reportMissingTypeStubs = false
reportUnknownMemberType = "warning"
reportMissingSuperCall = true

[language-server.pyright.config.python.analysis]
typeCheckingMode = "strict"
diagnosticMode = "workspace"
autoImportCompletions = true
strictListInference = true
strictDictionaryInference = true
strictSetInference = true

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.ruff.config.settings]
lint.preview =true


[language-server.rust-analyzer.config.check]
command = "clippy"


[language-server.scls]
command = "simple-completion-language-server"
config = {max_completion_items = 20, snippets_first = false}


[language-server.powershell]
command = "pwsh"
args = ["-NoLogo", "-NoProfile", "-Command", 'C:\PowerShellEditorServices\Start-EditorServices.ps1 -Stdio']

