[[language]]
name = "rust"
auto-format = true
indent = {tab-width = 4, unit = "    "}
language-servers = ["scls", "rust-analyzer"]

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py", "pyi", "py3", "pyw", "pt1", ".pythonstartup", ".pythonrc", "SConstruct"]
shebangs = ["python"]
roots = [".","steup.py", "setup.cfg", "pyproject.toml"]
comment-token = "#"
language-servers = ["scls", "pyright", "ruff"]
indent = {tab-width = 4, unit = "    "}
formatter = {command = "black", args=["--quiet", "-"]}
auto-format = true

[[language]]
name = "pwsh"
scope = "source.ps1"
roots = [".git", "."]
file-types = ["ps1"]
comment-token = "#"
indent = {tab-width = 2, unit = "  "}
language-servers = ["scls"]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config]
reportMissingTypeStubs = false
reportUnknownMemberType = "warning"
reportMissingSuperCall = true

[language-server.pyright.config.python.analysis]
typeCheckingMode = "strict"
autoImportCompletions = true

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config]
settings = {args=[]}

[[language]]
name = "json"
auto-format = true
# config = { "providerFormatter" = true, "json" = {"keeplines" = {"enable" = true}}}
indent = { tab-width = 2, unit = "  "}

[language-server.scls]
command = "simple-completion-language-server"
config = {max_completion_items = 20, snippets_first = false}

[language-server.scls.environment]
RUST_LOG = "debug,simple-completion-language-server=debug"
LOG_FILE = "c:/users/dweis/AppData/local/temp/completion.log"

# [language-server.powershell]
# command = "pwsh"
# args = ["-NoLogo", "-NoProfile", "-Command", 'C:\users\dweis\PowerShellEditorServices\Start-EditorServices.ps1 -BundledModulesPath C:\users\dweis\PowerShellEditorServices -LogPath C:\users\dweis\PowerShellEditorServices\pwsh-es.log -SessionDetailsPath C:\users\dweis\PowerShellEditorServices\pwsh-es.session.json -FeatureFlags @() -AdditionalModules @() -HostName "Helix" -HostProfileId 0 -HostVersion 1.0.0 -LogLevel Normal']

